<a href="https://colab.research.google.com/github/Tdanso/Micro-Credential-Winter-22/blob/main/Day_5_Intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to numpy

In [ ]:
import numpy as np

In [ ]:
np_city = np.array(['NYC', 'LA', 'Maimi', 'Houston'])

In [ ]:
np_city.shape

(4,)

In [ ]:
np_city.size

4

In [ ]:
np_city.dtype

dtype('<U7')

In [ ]:
np_city2 = np.array([['NYC', 'LA', 'Maimi', 'Houston'], 
                     ['NY', 'CA', 'FL', 'TX']])

In [ ]:
np_city2.shape

(2, 4)

In [ ]:
np_city2.dtype

dtype('<U7')

In [ ]:
np_city2.size

8

In [ ]:
# Create a np array with 5 lists in it... 
# each list must have 10 items in it

In [ ]:
first_trial_cyclist = [10, 15, 17, 26, 37, 49, 57, 61]

In [ ]:
second_trial_cyclist = [11, 45, 65, 24, 23, 45, 90, 99]

In [ ]:
np_first_trial = np.array(first_trial_cyclist)
np_second_trial = np.array(second_trial_cyclist)

In [ ]:
np_first_trial + np_second_trial

array([ 21,  60,  82,  50,  60,  94, 147, 160])

In [ ]:
np_first_trial[1] * np_second_trial[5]

675

In [ ]:
cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [ ]:
ftrail = cyclist_trial[0]

In [ ]:
ftrail

array([10, 15, 17, 26])

In [ ]:
newlist = ['string1', 'string2']

In [ ]:
newlist[0]

'string1'

In [ ]:
newlist[0][2]

'r'

In [ ]:
strail = cyclist_trial[1]

In [ ]:
strail

array([12, 11, 21, 24])

In [ ]:
ftrail[1] # this is the same as saying cyclist_trial[0][1]

15

In [ ]:
cyclist_trial[0][1]

15

In [ ]:
test_score = np.array([[83, 71, 67, 63],[54, 68, 81, 45]])

In [ ]:
passsed = test_score > 60

In [ ]:
passsed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
test2_scores = test_score

In [ ]:
test_score is test2_scores

True

In [ ]:
test2_scores[1][3] = 78

In [ ]:
test2_scores

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
test_score

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
NYC_Boroughs = np.array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'])

In [ ]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'],
      dtype='<U13')

In [ ]:
NY_Boroughs = NYC_Boroughs.view()

In [ ]:
len(NY_Boroughs)

5

In [ ]:
NY_Boroughs[4] = 'Central Park'

In [ ]:
len(NY_Boroughs)

5

In [ ]:
NY_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC_Boroughs is NY_Boroughs

False

In [ ]:
NYC = NYC_Boroughs.copy()

In [ ]:
NYC is NYC_Boroughs

False

In [ ]:
NYC[4] = 'Astoria'

In [ ]:
NYC_Boroughs

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC

array(['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Astoria'],
      dtype='<U13')