<a href="https://colab.research.google.com/github/Tdanso/Micro-Credential-Winter-22/blob/main/day_5_intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# intro to Numpy

In [ ]:
import numpy as np
import math

In [ ]:
np_city =np.array(["NYC","LA","Miami", " Houston"])

In [ ]:
np_city

array(['NYC', 'LA', 'Miami', ' Houston'], dtype='<U8')

In [ ]:
np_city.shape

(4,)

In [ ]:
np_city.size

4

In [ ]:
np_city.dtype

dtype('<U8')

In [ ]:
np_city2 =np.array([["NYC","LA","Miami", " Houston"],
                   ["NY","CA","FL","TX"]])

In [ ]:
np_city2

array([['NYC', 'LA', 'Miami', ' Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U8')

In [ ]:
np_city2.shape

(2, 4)

In [ ]:
np_city2.size

8

In [ ]:
np_city2.dtype

dtype('<U8')

# Create a np array with 5 lists in it... 
# each list must have 10 items in it

In [ ]:
data = np.array([["A","B","C","D","E","F","G"],
                ["A","B","C","D","E","F", "G"],
                 ["A","B","C","D","E","F","G"],
                 ["A","B","C","D","E","F", "G"],
                 ["A","B","C","D","E","F", "G"]])
data

In [ ]:
data.size

35

In [ ]:
first_trial_cylist = ["10","15","17","26","37","49","57","61"]


In [ ]:
second_trial_cylist = ["10","15","20","20","30","49","50","60"]

In [ ]:
np_first_trial = np.array(first_trial_cylist)
np_second_trial = np.array(second_trial_cylist)

In [ ]:
np_second_trial

array(['10', '15', '20', '20', '30', '49', '50', '60'], dtype='<U2')

In [ ]:
np_first_trial + np_second_trial

In [ ]:
np_first_trial[1] * np_second_trial[5]

In [ ]:
for i in range(len()first_trial_cyclist):
  for ...:
    for 

In [ ]:
cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [ ]:
cyclist_trial


array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [ ]:
ftrail = cyclist_trial[0]
ftrail

array([10, 15, 17, 26])

In [ ]:
newlist = ['string1', 'string2']

In [ ]:
newlist[0]

'string1'

In [ ]:
ftrail = cyclist_trial[1]
ftrail

array([12, 11, 21, 24])

In [ ]:
newlist[0][2]


'r'

In [ ]:
ftrail[1] # this is the same as saying 

In [ ]:
cyclist_trial[0][1]

15

In [ ]:
test_score = np.array([[83, 71, 67, 63],[54,68,81,45]])

In [ ]:
passsed = test_score > 60
passsed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
test2_scores = test_score

In [ ]:
test_score is test2_scores

True

In [ ]:
test2_scores[1][3] = 78

test2_scores

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
 NYC_Broughts = np.array(["Manhattan", "Bronx", "Brooklyn", "Queens", "Staten Island"])
 NYC_Broughts

array(['Manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Staten Island'],
      dtype='<U13')

In [ ]:
NY_Broughts = NYC_Broughts.view()

In [ ]:
len(NYC_Broughts)

5

In [ ]:
NY_Broughts[4] = "Central Park"
NY_Broughts

array(['Manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Central Park'],
      dtype='<U13')

In [ ]:
NYC_Broughts is NY_Broughts

False